name: build javadocs

on:
  push:
    branches:
      - main
      - develop
      - yamlDocs
jobs:
  javadoc_build:
    runs-on: ubuntu-latest
    name: Building the javadocs to html.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          #I think above and below are correct. The build container portion is what I need to figure out. 
      #- name: Get build container
       # id: adocbuild
        #uses: tonynv/asciidoctor-action@master
        #with:
         # program: "./gradlew asciidoctor"
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./micronautpi4j-utils/build/docs/javadoc/

